### ISSUE TITLE
it is not specified which fonts are used

### ISSUE THREAD

**Issue by Spbog** [ashish-kus/dotfiles#1]
your dotfiles do not indicate which fonts are used. it would be good if you wrote a list of fonts or added a .fonts folder

**Comment by ashish-kus** [comment]
I apologize for not mentioning the fonts earlier. They are Maple Mono and JetBrains Mono.

**Comment by Spbog** [comment]
thanks. and what font is used for the battery icon on lockscreen?

**Comment by ashish-kus** [comment]
In hyprlock i used Nerd Fonts
